# generated by datamodel-codegen:
#   filename:  hotmart-api.json
#   timestamp: 2026-05-14T21:03:32+00:00

from __future__ import annotations

from enum import IntEnum, StrEnum as _StdStrEnum
from typing import Any

from pydantic import BaseModel as _PydanticBase, ConfigDict, Field, confloat, constr
from pydantic_core import core_schema


class StrEnum(_StdStrEnum):
    """Permissive StrEnum — unknown API values pass through as raw strings
    instead of raising ValidationError.

    Hotmart's spec lags behind production (e.g. PaymentType ships APPLE_PAY
    before the OpenAPI doc lists it). Strict enum validation would crash the
    whole dashboard for one unknown value. This Pydantic schema tries the
    enum first, falls back to a raw str so downstream code keeps working.
    Access via `str(value)` either way since StrEnum members ARE strings.
    """
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        def coerce(v):
            if v is None or isinstance(v, cls): return v
            try: return cls(v)
            except (ValueError, KeyError): return v
        return core_schema.no_info_plain_validator_function(coerce)


class BaseModel(_PydanticBase):
    """Allow API to return extra fields the spec didn't declare.

    Hotmart's OpenAPI spec is occasionally incomplete (e.g. Product
    declares only name+id but production returns format/status/created_at).
    `extra='allow'` lets those land in `.model_extra` instead of failing
    validation — so we keep schema enforcement on declared fields while
    still surfacing extras when needed.
    """
    model_config = ConfigDict(extra='allow')


class PageInfo(BaseModel):
    """
    Informações de paginação
    """

    total_results: int | None = Field(None, description='Total de resultados')
    next_page_token: str | None = Field(None, description='Token para a próxima página')
    prev_page_token: str | None = Field(
        None, description='Token para a página anterior'
    )
    results_per_page: int | None = Field(
        None, description='Número de resultados por página'
    )


class Price(BaseModel):
    """
    Representação de valor monetário
    """

    value: float | None = Field(None, description='Valor')
    currency_code: str | None = Field(None, description='Código da moeda (ISO 4217)')


class TransactionStatus(StrEnum):
    """
    Status da transação
    """

    APPROVED = 'APPROVED'
    BLOCKED = 'BLOCKED'
    CANCELLED = 'CANCELLED'
    CHARGEBACK = 'CHARGEBACK'
    COMPLETE = 'COMPLETE'
    EXPIRED = 'EXPIRED'
    NO_FUNDS = 'NO_FUNDS'
    OVERDUE = 'OVERDUE'
    PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED'
    PRE_ORDER = 'PRE_ORDER'
    PRINTED_BILLET = 'PRINTED_BILLET'
    PROCESSING_TRANSACTION = 'PROCESSING_TRANSACTION'
    PROTESTED = 'PROTESTED'
    REFUNDED = 'REFUNDED'
    STARTED = 'STARTED'
    UNDER_ANALISYS = 'UNDER_ANALISYS'
    WAITING_PAYMENT = 'WAITING_PAYMENT'


class PaymentType(StrEnum):
    """
    Tipo de pagamento
    """

    BILLET = 'BILLET'
    CASH_PAYMENT = 'CASH_PAYMENT'
    CREDIT_CARD = 'CREDIT_CARD'
    DIRECT_BANK_TRANSFER = 'DIRECT_BANK_TRANSFER'
    DIRECT_DEBIT = 'DIRECT_DEBIT'
    FINANCED_BILLET = 'FINANCED_BILLET'
    FINANCED_INSTALLMENT = 'FINANCED_INSTALLMENT'
    GOOGLE_PAY = 'GOOGLE_PAY'
    HOTCARD = 'HOTCARD'
    HYBRID = 'HYBRID'
    MANUAL_TRANSFER = 'MANUAL_TRANSFER'
    PAYPAL = 'PAYPAL'
    PAYPAL_INTERNACIONAL = 'PAYPAL_INTERNACIONAL'
    PICPAY = 'PICPAY'
    PIX = 'PIX'
    SAMSUNG_PAY = 'SAMSUNG_PAY'
    WALLET = 'WALLET'


class PaymentMethod(StrEnum):
    """
    Método de pagamento detalhado
    """

    BACS_DIRECT_DEBIT = 'BACS_DIRECT_DEBIT'
    BALOTO = 'BALOTO'
    BANK_DEBIT = 'BANK_DEBIT'
    BILLET = 'BILLET'
    CREDIT_CARD_AMERICAN_EXPRESS = 'CREDIT_CARD_AMERICAN_EXPRESS'
    CREDIT_CARD_AURA = 'CREDIT_CARD_AURA'
    CREDIT_CARD_DINERS = 'CREDIT_CARD_DINERS'
    CREDIT_CARD_DISCOVER = 'CREDIT_CARD_DISCOVER'
    CREDIT_CARD_ELO = 'CREDIT_CARD_ELO'
    CREDIT_CARD_HIPERCARD = 'CREDIT_CARD_HIPERCARD'
    CREDIT_CARD_MASTERCARD = 'CREDIT_CARD_MASTERCARD'
    CREDIT_CARD_VISA = 'CREDIT_CARD_VISA'
    CUPON_DE_PAGO = 'CUPON_DE_PAGO'
    DIRECT_BANK_TRANSFER_ADYEN_SOFORT = 'DIRECT_BANK_TRANSFER_ADYEN_SOFORT'
    FINANCED_BILLET = 'FINANCED_BILLET'
    FINANCED_INSTALLMENT_ADYEN_ONEY = 'FINANCED_INSTALLMENT_ADYEN_ONEY'
    FINANCED_INSTALLMENT_ADYEN_ONEY_10X = 'FINANCED_INSTALLMENT_ADYEN_ONEY_10X'
    FINANCED_INSTALLMENT_ADYEN_ONEY_12X = 'FINANCED_INSTALLMENT_ADYEN_ONEY_12X'
    FINANCED_INSTALLMENT_ADYEN_ONEY_3X = 'FINANCED_INSTALLMENT_ADYEN_ONEY_3X'
    FINANCED_INSTALLMENT_ADYEN_ONEY_4X = 'FINANCED_INSTALLMENT_ADYEN_ONEY_4X'
    FINANCED_INSTALLMENT_ADYEN_ONEY_6X = 'FINANCED_INSTALLMENT_ADYEN_ONEY_6X'
    GOOGLE_PAY = 'GOOGLE_PAY'
    HOTMART = 'HOTMART'
    HYBRID = 'HYBRID'
    IN_APP_PURCHASE = 'IN_APP_PURCHASE'
    MULTIBANCO = 'MULTIBANCO'
    OXXO = 'OXXO'
    PAGO_EFECTIVO = 'PAGO_EFECTIVO'
    PAYPAL = 'PAYPAL'
    PICPAY = 'PICPAY'
    PIX = 'PIX'
    SAMSUNG_PAY = 'SAMSUNG_PAY'
    SEPA_DIRECT_DEBIT = 'SEPA_DIRECT_DEBIT'
    BANK_TRANSFER_BB = 'BANK_TRANSFER_BB'
    BANK_TRANSFER_BRADESCO = 'BANK_TRANSFER_BRADESCO'
    BANK_TRANSFER_ITAU = 'BANK_TRANSFER_ITAU'
    APPLE_PAY = 'APPLE_PAY'


class CommissionAs(StrEnum):
    """
    Papel de comissão
    """

    PRODUCER = 'PRODUCER'
    COPRODUCER = 'COPRODUCER'
    AFFILIATE = 'AFFILIATE'


class SubscriptionStatus(StrEnum):
    """
    Status da assinatura
    """

    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    DELAYED = 'DELAYED'
    CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER'
    CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER'
    CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN'
    STARTED = 'STARTED'
    OVERDUE = 'OVERDUE'


class BillingType(StrEnum):
    """
    Tipo de cobrança
    """

    SUBSCRIPTION = 'SUBSCRIPTION'
    SMART_INSTALLMENT = 'SMART_INSTALLMENT'
    SMART_RECOVERY = 'SMART_RECOVERY'


class ProductStatus(StrEnum):
    """
    Status do produto
    """

    DRAFT = 'DRAFT'
    ACTIVE = 'ACTIVE'
    PAUSED = 'PAUSED'
    NOT_APPROVED = 'NOT_APPROVED'
    IN_REVIEW = 'IN_REVIEW'
    DELETED = 'DELETED'
    CHANGES_PENDING_ON_PRODUCT = 'CHANGES_PENDING_ON_PRODUCT'


class ProductFormat(StrEnum):
    """
    Formato do produto
    """

    EBOOK = 'EBOOK'
    SOFTWARE = 'SOFTWARE'
    MOBILE_APPS = 'MOBILE_APPS'
    VIDEOS = 'VIDEOS'
    AUDIOS = 'AUDIOS'
    TEMPLATES = 'TEMPLATES'
    IMAGES = 'IMAGES'
    ONLINE_COURSE = 'ONLINE_COURSE'
    SERIAL_CODES = 'SERIAL_CODES'
    ETICKET = 'ETICKET'
    ONLINE_SERVICE = 'ONLINE_SERVICE'
    ONLINE_EVENT = 'ONLINE_EVENT'
    BUNDLE = 'BUNDLE'
    COMMUNITY = 'COMMUNITY'


class TicketStatus(StrEnum):
    """
    Status do ingresso
    """

    SOLD = 'SOLD'
    INVITE = 'INVITE'
    INVITE_CANCELED = 'INVITE_CANCELED'
    REFUNDED = 'REFUNDED'
    CHARGEBACK = 'CHARGEBACK'
    EXCLUDED = 'EXCLUDED'
    AVAILABLE = 'AVAILABLE'
    RESERVED = 'RESERVED'


class TicketType(StrEnum):
    """
    Tipo do ingresso
    """

    PAID = 'PAID'
    FREE = 'FREE'
    ALL = 'ALL'


class CheckinStatus(StrEnum):
    """
    Status do check-in
    """

    PENDING = 'PENDING'
    PARTIAL = 'PARTIAL'
    CONCLUDED = 'CONCLUDED'
    ALL = 'ALL'


class ErrorResponse(BaseModel):
    error: str | None = Field(None, description='Código do erro')
    error_description: str | None = Field(None, description='Descrição do erro')
    error_uri: str | None = Field(None, description='URI de referência do erro')


class Product(BaseModel):
    name: str | None = Field(None, description='Nome do produto')
    id: int | None = Field(None, description='ID do produto')


class Buyer(BaseModel):
    name: str | None = Field(None, description='Nome do comprador')
    ucode: str | None = Field(None, description='Código único do comprador')
    email: str | None = Field(None, description='E-mail do comprador')


class Producer(BaseModel):
    name: str | None = Field(None, description='Nome do produtor')
    ucode: str | None = Field(None, description='Código único do produtor')


class Payment(BaseModel):
    method: str | None = Field(None, description='Método de pagamento')
    installments_number: int | None = Field(None, description='Número de parcelas')
    type: PaymentType | None = None


class Tracking(BaseModel):
    source_sck: str | None = Field(None, description='Source SCK de rastreamento')
    source: str | None = Field(None, description='Fonte de rastreamento')
    external_code: str | None = Field(
        None, description='Código externo de rastreamento'
    )


class Offer(BaseModel):
    payment_mode: str | None = Field(None, description='Modo de pagamento da oferta')
    code: str | None = Field(None, description='Código da oferta')


class HotmartFee(BaseModel):
    total: float | None = Field(None, description='Taxa total da Hotmart')
    fixed: float | None = Field(None, description='Taxa fixa')
    currency_code: str | None = Field(None, description='Código da moeda')
    base: float | None = Field(None, description='Base de cálculo')
    percentage: float | None = Field(None, description='Percentual da taxa')


class Purchase(BaseModel):
    transaction: str | None = Field(None, description='Código da transação')
    order_date: int | None = Field(None, description='Data do pedido (timestamp ms)')
    approved_date: int | None = Field(
        None, description='Data de aprovação (timestamp ms)'
    )
    status: TransactionStatus | None = None
    recurrency_number: int | None = Field(None, description='Número da recorrência')
    is_subscription: bool | None = Field(None, description='Se é assinatura')
    commission_as: CommissionAs | None = None
    price: Price | None = None
    payment: Payment | None = None
    tracking: Tracking | None = None
    warranty_expire_date: int | None = Field(
        None, description='Data de expiração da garantia (timestamp ms)'
    )
    offer: Offer | None = None
    hotmart_fee: HotmartFee | None = None


class SaleHistory(BaseModel):
    product: Product | None = None
    buyer: Buyer | None = None
    producer: Producer | None = None
    purchase: Purchase | None = None


class SaleSummary(BaseModel):
    total_items: int | None = Field(None, description='Total de itens')
    total_value: Price | None = None


class Product1(BaseModel):
    name: str | None = None
    id: int | None = None


class Role(StrEnum):
    """
    Papel do participante
    """

    PRODUCER = 'PRODUCER'
    AFFILIATE = 'AFFILIATE'
    COPRODUCER = 'COPRODUCER'


class Document(BaseModel):
    type: str | None = Field(None, description='Tipo do documento')
    value: str | None = Field(None, description='Valor do documento')


class Address(BaseModel):
    city: str | None = None
    state: str | None = None
    country: str | None = None
    zip_code: str | None = None
    address: str | None = None
    complement: str | None = None
    neighborhood: str | None = None
    number: str | None = None


class User1(BaseModel):
    ucode: str | None = Field(None, description='Código único do usuário')
    locale: str | None = Field(None, description='Localidade do usuário')
    name: str | None = Field(None, description='Nome')
    trade_name: str | None = Field(None, description='Nome comercial')
    cellphone: str | None = Field(None, description='Celular')
    phone: str | None = Field(None, description='Telefone')
    email: str | None = Field(None, description='E-mail')
    documents: list[Document] | None = None
    address: Address | None = None


class User(BaseModel):
    role: Role | None = Field(None, description='Papel do participante')
    user: User1 | None = None


class SaleParticipant(BaseModel):
    transaction: str | None = Field(None, description='Código da transação')
    product: Product1 | None = None
    users: list[User] | None = None


class Commission1(BaseModel):
    currency_value: float | None = Field(None, description='Valor na moeda local')
    value: float | None = Field(None, description='Valor da comissão')


class User2(BaseModel):
    ucode: str | None = None
    name: str | None = None


class Source(StrEnum):
    """
    Fonte da comissão
    """

    PRODUCER = 'PRODUCER'
    COPRODUCER = 'COPRODUCER'
    ADDON = 'ADDON'


class Commission(BaseModel):
    commission: Commission1 | None = None
    user: User2 | None = None
    source: Source | None = Field(None, description='Fonte da comissão')


class SaleCommission(BaseModel):
    transaction: str | None = Field(None, description='Código da transação')
    product: Product1 | None = None
    exchange_rate_currency_payout: float | None = Field(
        None, description='Taxa de câmbio para pagamento'
    )
    commissions: list[Commission] | None = None


class Product3(BaseModel):
    id: int | None = None
    name: str | None = None


class Coupon(BaseModel):
    code: str | None = Field(None, description='Código do cupom')
    value: float | None = Field(None, description='Valor do desconto')


class SalePriceDetail(BaseModel):
    transaction: str | None = Field(None, description='Código da transação')
    product: Product3 | None = None
    base: Price | None = None
    total: Price | None = None
    vat: Price | None = None
    fee: Price | None = None
    coupon: Coupon | None = None
    real_conversion_rate: float | None = Field(
        None, description='Taxa de conversão real'
    )


class Plan(BaseModel):
    name: str | None = Field(None, description='Nome do plano')
    id: int | None = Field(None, description='ID do plano')
    recurrency_period: str | None = Field(None, description='Período de recorrência')
    max_charge_cycles: int | None = Field(
        None, description='Máximo de ciclos de cobrança'
    )


class Product4(BaseModel):
    id: int | None = None
    name: str | None = None
    ucode: str | None = None


class Subscriber(BaseModel):
    name: str | None = None
    email: str | None = None
    ucode: str | None = None


class Subscription(BaseModel):
    subscriber_code: str | None = Field(None, description='Código do assinante')
    subscription_id: int | None = Field(None, description='ID da assinatura')
    status: SubscriptionStatus | None = None
    accession_date: int | None = Field(
        None, description='Data de adesão (timestamp ms)'
    )
    end_accession_date: int | None = Field(
        None, description='Data final de adesão (timestamp ms)'
    )
    request_date: int | None = Field(
        None, description='Data da solicitação (timestamp ms)'
    )
    date_next_charge: int | None = Field(
        None, description='Data da próxima cobrança (timestamp ms)'
    )
    trial: bool | None = Field(None, description='Se está em trial')
    transaction: str | None = Field(None, description='Código da transação')
    plan: Plan | None = None
    product: Product4 | None = None
    price: Price | None = None
    subscriber: Subscriber | None = None


class Plan1(BaseModel):
    name: str | None = None
    recurrency_period: str | None = None


class Product5(BaseModel):
    name: str | None = None
    id: int | None = None


class Offer1(BaseModel):
    code: str | None = None


class LastRecurrency(BaseModel):
    number: int | None = Field(None, description='Número da última recorrência')
    request_date: int | None = None
    status: str | None = None
    transaction_number: str | None = None
    billing_type: BillingType | None = None


class UnpaidRecurrency(BaseModel):
    number: int | None = None
    charge_date: int | None = None


class Subscriber1(BaseModel):
    name: str | None = None
    id: str | None = None
    email: str | None = None


class SubscriptionSummary(BaseModel):
    subscriber_code: str | None = None
    subscription_id: int | None = None
    status: SubscriptionStatus | None = None
    lifetime: int | None = Field(
        None, description='Tempo de vida da assinatura em dias'
    )
    accession_date: int | None = None
    end_accession_date: int | None = None
    trial: bool | None = None
    plan: Plan1 | None = None
    product: Product5 | None = None
    offer: Offer1 | None = None
    last_recurrency: LastRecurrency | None = None
    unpaid_recurrencies: list[UnpaidRecurrency] | None = None
    subscriber: Subscriber1 | None = None


class Subscriber2(BaseModel):
    phone: str | None = None
    name: str | None = None
    id: str | None = None
    phone_ddd: str | None = None
    email: str | None = None


class Recurrency(BaseModel):
    number: int | None = None
    scheduled_retry: bool | None = None
    number_list: list[int] | None = None
    transaction_sequence: int | None = None
    start_datetime: int | None = None
    payment_delays_days: int | None = None
    transaction_type: str | None = None
    is_current_purchase: bool | None = None
    has_retry: bool | None = None
    status: str | None = None


class TrialInfo(BaseModel):
    trial_end: int | None = None
    trial_period: int | None = None
    trial: bool | None = None


class Price1(BaseModel):
    total_value: float | None = None
    currency: str | None = None
    value: float | None = None


class Installment(BaseModel):
    installment_number: int | None = None
    installment_type: str | None = None


class Payment1(BaseModel):
    refusal_message: str | None = None
    refund_chargeback_date: int | None = None
    payment_type: PaymentType | None = None
    billet_expiration_date: int | None = None
    billet_recovery_type: str | None = None
    pix_expiration_date: int | None = None
    billet_reprint_code: str | None = None
    credit_card_flag: str | None = None


class Commission2(BaseModel):
    original_value: float | None = None
    producer_paid_value: float | None = None
    currency: str | None = None
    original_paid_value: float | None = None
    conversion_rate: float | None = None
    producer_value: float | None = None


class Purchase1(BaseModel):
    order_date: int | None = None
    price: Price1 | None = None
    installment: Installment | None = None
    payment: Payment1 | None = None
    commission: Commission2 | None = None
    approved_date: int | None = None
    transaction: str | None = None
    status: TransactionStatus | None = None


class Producer1(BaseModel):
    name: str | None = None


class Offer2(BaseModel):
    code: str | None = None
    description: str | None = None
    key: str | None = None


class Plan2(BaseModel):
    offer: Offer2 | None = None
    recurrency_period: str | None = None
    coupon_code: str | None = None
    recurrency_type: str | None = None
    name: str | None = None


class SubscriptionTransaction(BaseModel):
    last_recurrency_start_date: int | None = None
    has_unpaid_recurrency: bool | None = None
    product: Product5 | None = None
    subscriber: Subscriber2 | None = None
    recurrency: Recurrency | None = None
    last_recurrency_number: int | None = None
    trial_info: TrialInfo | None = None
    purchase: Purchase1 | None = None
    cancellation_date: int | None = None
    is_paid_anticipation: bool | None = None
    max_cycles: int | None = None
    adoption_date: int | None = None
    subscriber_code: str | None = None
    date_next_charge: int | None = None
    is_paid_negotiation: bool | None = None
    last_update: int | None = None
    billing_type: BillingType | None = None
    producer: Producer1 | None = None
    subscription_id: int | None = None
    has_credit_card_change: bool | None = None
    plan: Plan2 | None = None
    status: SubscriptionStatus | None = None


class SubscriberPurchase(BaseModel):
    transaction: str | None = Field(None, description='Código da transação')
    approved_date: int | None = Field(
        None, description='Data de aprovação (timestamp ms)'
    )
    payment_engine: str | None = Field(None, description='Motor de pagamento')
    status: TransactionStatus | None = None
    price: Price | None = None
    payment_type: PaymentType | None = None
    payment_method: PaymentMethod | None = None
    recurrency_number: int | None = Field(None, description='Número da recorrência')
    under_warranty: bool | None = Field(None, description='Se está dentro da garantia')
    purchase_subscription: bool | None = Field(
        None, description='Se é compra de assinatura'
    )


class Status(StrEnum):
    """
    Status após cancelamento
    """

    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class IntervalTypeBetweenCharges(StrEnum):
    DAY = 'DAY'
    WEEK = 'WEEK'
    MONTH = 'MONTH'
    INVOICE = 'INVOICE'


class Shopper(BaseModel):
    email: str | None = None
    phone: str | None = None


class SubscriptionCancelResponse(BaseModel):
    status: Status | None = Field(None, description='Status após cancelamento')
    subscriber_code: str | None = None
    creation_date: int | None = None
    current_recurrence: int | None = None
    date_last_recurrence: int | None = None
    date_next_charge: int | None = None
    due_day: int | None = None
    trial_period: int | None = None
    interval_type_between_charges: IntervalTypeBetweenCharges | None = None
    interval_between_charges: int | None = None
    max_charge_cycles: int | None = None
    activation_date: int | None = None
    shopper: Shopper | None = None


class FailSubscription(BaseModel):
    status: str | None = None
    error: str | None = None
    subscriber_code: str | None = None
    creation_date: int | None = None
    interval_between_charges: int | None = None
    shopper: Shopper | None = None


class BatchSubscriptionResult(BaseModel):
    success_subscriptions: list[SubscriptionCancelResponse] | None = None
    fail_subscriptions: list[FailSubscription] | None = None


class Status1(StrEnum):
    """
    Status da assinatura (INACTIVE até o assinante aceitar via e-mail)
    """

    INACTIVE = 'INACTIVE'


class IntervalBetweenCharges(IntEnum):
    """
    Intervalo entre cobranças em dias
    """

    integer_7 = 7
    integer_30 = 30
    integer_60 = 60
    integer_90 = 90
    integer_180 = 180
    integer_360 = 360


class SubscriptionReactivateResponse(BaseModel):
    status: Status1 | None = Field(
        None,
        description='Status da assinatura (INACTIVE até o assinante aceitar via e-mail)',
    )
    subscriber_code: str | None = None
    creation_date: int | None = None
    interval_between_charges: IntervalBetweenCharges | None = Field(
        None, description='Intervalo entre cobranças em dias'
    )
    shopper: Shopper | None = None


class FailSubscription1(BaseModel):
    status: str | None = None
    error: str | None = None
    subscriber_code: str | None = None
    creation_date: int | None = None
    interval_between_charges: int | None = None
    shopper: Shopper | None = None


class BatchSubscriptionReactivateResult(BaseModel):
    success_subscriptions: list[SubscriptionReactivateResponse] | None = None
    fail_subscriptions: list[FailSubscription1] | None = None


class Module(BaseModel):
    module_id: str | None = Field(None, description='ID do módulo')
    name: str | None = Field(None, description='Nome do módulo')
    sequence: int | None = Field(None, description='Sequência do módulo')
    is_public: bool | None = Field(None, description='Se é público')
    is_extra: bool | None = Field(None, description='Se é módulo extra')
    is_extra_paid: bool | None = Field(None, description='Se é módulo extra pago')
    classes: list[dict[str, Any]] | None = Field(None, description='Aulas do módulo')
    total_pages: int | None = Field(None, description='Total de páginas no módulo')


class Type(StrEnum):
    """
    Tipo da página
    """

    CONTENT = 'CONTENT'
    ADVERTISEMENT = 'ADVERTISEMENT'
    QUIZ = 'QUIZ'
    WEBINAR = 'WEBINAR'


class Rate(BaseModel):
    rate: int | None = Field(None, description='Nota')
    total: int | None = Field(None, description='Total de avaliações com esta nota')


class LiberationType(StrEnum):
    """
    Tipo de liberação
    """

    BY_DATE = 'BY_DATE'
    BY_DAYS = 'BY_DAYS'


class Page(BaseModel):
    page_id: str | None = Field(None, description='ID da página')
    name: str | None = Field(None, description='Nome da página')
    page_order: int | None = Field(None, description='Ordem da página')
    type: Type | None = Field(None, description='Tipo da página')
    is_published: bool | None = Field(None, description='Se está publicada')
    total_comments: int | None = Field(None, description='Total de comentários')
    rates_average: float | None = Field(None, description='Média de avaliações')
    rates: list[Rate] | None = None
    has_media: bool | None = Field(None, description='Se possui mídia')
    liberation_type: LiberationType | None = Field(
        None, description='Tipo de liberação'
    )
    liberation_date: int | None = Field(
        None, description='Data de liberação (timestamp ms)'
    )
    liberation_days: int | None = Field(None, description='Dias para liberação')
    has_duration: bool | None = Field(None, description='Se tem duração definida')
    days_of_duration: int | None = Field(None, description='Dias de duração')


class Engagement(StrEnum):
    """
    Nível de engajamento
    """

    NONE = 'NONE'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class Role1(StrEnum):
    """
    Papel do aluno
    """

    STUDENT = 'STUDENT'
    FREE_STUDENT = 'FREE_STUDENT'
    OWNER = 'OWNER'
    ADMIN = 'ADMIN'
    CONTENT_EDITOR = 'CONTENT_EDITOR'
    MODERATOR = 'MODERATOR'


class PlusAccess(StrEnum):
    """
    Tipo de acesso Plus
    """

    WITHOUT_PLUS_ACCESS = 'WITHOUT_PLUS_ACCESS'
    HOLDER = 'HOLDER'
    HOLDER_WITH_DEPENDENTS = 'HOLDER_WITH_DEPENDENTS'
    HOLDER_WITHOUT_DEPENDENTS = 'HOLDER_WITHOUT_DEPENDENTS'
    DEPENDENT = 'DEPENDENT'


class Progress(BaseModel):
    completed_percentage: float | None = Field(None, description='Percentual concluído')
    total: int | None = Field(None, description='Total de aulas')
    completed: int | None = Field(None, description='Aulas concluídas')


class Status2(StrEnum):
    """
    Status do aluno
    """

    ACTIVE = 'ACTIVE'
    BLOCKED = 'BLOCKED'
    BLOCKED_BY_OWNER = 'BLOCKED_BY_OWNER'
    OVERDUE = 'OVERDUE'


class Type1(StrEnum):
    """
    Tipo do aluno
    """

    BUYER = 'BUYER'
    IMPORTED = 'IMPORTED'
    FREE = 'FREE'
    OWNER = 'OWNER'
    GUEST = 'GUEST'


class Student(BaseModel):
    user_id: str | None = Field(None, description='ID do aluno')
    engagement: Engagement | None = Field(None, description='Nível de engajamento')
    name: str | None = Field(None, description='Nome do aluno')
    email: str | None = Field(None, description='E-mail do aluno')
    last_access_date: int | None = Field(
        None, description='Data do último acesso (timestamp ms)'
    )
    role: Role1 | None = Field(None, description='Papel do aluno')
    first_access_date: int | None = Field(
        None, description='Data do primeiro acesso (timestamp ms)'
    )
    locale: str | None = Field(None, description='Localidade do aluno')
    plus_access: PlusAccess | None = Field(None, description='Tipo de acesso Plus')
    progress: Progress | None = None
    status: Status2 | None = Field(None, description='Status do aluno')
    purchase_date: int | None = Field(None, description='Data da compra (timestamp ms)')
    access_count: int | None = Field(None, description='Número de acessos')
    is_deletable: bool | None = Field(None, description='Se pode ser excluído')
    class_id: str | None = Field(None, description='ID da turma')
    type: Type1 | None = Field(None, description='Tipo do aluno')


class LessonProgress(BaseModel):
    page_id: str | None = Field(None, description='ID da página/aula')
    page_name: str | None = Field(None, description='Nome da página/aula')
    module_name: str | None = Field(None, description='Nome do módulo')
    is_module_extra: bool | None = Field(None, description='Se o módulo é extra')
    is_completed: bool | None = Field(None, description='Se a aula foi concluída')
    completed_date: int | None = Field(
        None, description='Data de conclusão (timestamp ms)'
    )


class Product7(BaseModel):
    id: int | None = Field(None, description='ID do produto')
    name: str | None = Field(None, description='Nome do produto')
    ucode: str | None = Field(None, description='Código único do produto')
    status: ProductStatus | None = None
    created_at: int | None = Field(None, description='Data de criação (timestamp ms)')
    format: ProductFormat | None = None
    is_subscription: bool | None = Field(None, description='Se é produto de assinatura')
    warranty_period: int | None = Field(None, description='Período de garantia em dias')


class PaymentTypesPrice(BaseModel):
    payment_type: str | None = None
    value: float | None = None


class Price2(BaseModel):
    currency_code: str | None = None
    value: float | None = None
    payment_types_prices: list[PaymentTypesPrice] | None = None


class Offer3(BaseModel):
    key: str | None = Field(None, description='Chave da oferta')
    status: str | None = Field(None, description='Status da oferta')
    name: str | None = Field(None, description='Nome da oferta')
    payment_mode: str | None = Field(None, description='Modo de pagamento')
    offer_payment_type: str | None = Field(
        None, description='Tipo de pagamento da oferta'
    )
    max_charge_cycles: int | None = Field(
        None, description='Máximo de ciclos de cobrança'
    )
    prices: list[Price2] | None = None
    is_subscription: bool | None = Field(None, description='Se é oferta de assinatura')


class Plan3(BaseModel):
    id: int | None = Field(None, description='ID do plano')
    name: str | None = Field(None, description='Nome do plano')
    max_charge_cycles: int | None = Field(
        None, description='Máximo de ciclos de cobrança'
    )
    recurrency_period: str | None = Field(None, description='Período de recorrência')


class CreateCouponRequest(BaseModel):
    code: constr(max_length=25) = Field(
        ..., description='Código do cupom (máximo 25 caracteres)'
    )
    discount: confloat(lt=0.99, gt=0.0) = Field(
        ..., description='Percentual de desconto (entre 0 e 0.99, exclusivo)'
    )
    start_date: int | None = Field(
        None, description='Data de início de validade (timestamp em milissegundos)'
    )
    end_date: int | None = Field(
        None, description='Data de fim de validade (timestamp em milissegundos)'
    )
    affiliate: int | None = Field(None, description='ID do afiliado')
    offer_ids: list[int] | None = Field(None, description='IDs das ofertas aplicáveis')


class TimeZone(BaseModel):
    offset: str | None = Field(None, description='Offset do fuso horário')
    description: str | None = Field(None, description='Descrição do fuso horário')
    id: str | None = Field(None, description='ID do fuso horário')
    name: str | None = Field(None, description='Nome do fuso horário')


class Coupon1(BaseModel):
    coupon_code: str | None = Field(None, description='Código do cupom')
    active: bool | None = Field(None, description='Se o cupom está ativo')
    start_date: int | None = Field(None, description='Data de início (timestamp ms)')
    discount: float | None = Field(None, description='Percentual de desconto')
    time_zone: TimeZone | None = None
    status: str | None = Field(None, description='Status do cupom')
    id: int | None = Field(None, description='ID do cupom')


class Product8(BaseModel):
    name: str | None = None
    id: int | None = None


class Lot(BaseModel):
    id: int | None = Field(None, description='ID do lote')
    name: str | None = Field(None, description='Nome do lote')


class EventInfo(BaseModel):
    product: Product8 | None = None
    start_event_date: int | None = Field(
        None, description='Data de início do evento (timestamp ms)'
    )
    end_event_date: int | None = Field(
        None, description='Data de fim do evento (timestamp ms)'
    )
    lots: list[Lot] | None = None


class Participant(BaseModel):
    email: str | None = None
    document: str | None = None
    id: str | None = None
    name: str | None = None
    phone: str | None = None


class Buyer1(BaseModel):
    ucode: str | None = None
    email: str | None = None
    name: str | None = None


class Eticket(BaseModel):
    ticket_qr_code: str | None = Field(None, description='QR code do ingresso')
    current_update: int | None = Field(
        None, description='Última atualização (timestamp ms)'
    )
    checkin_status: CheckinStatus | None = None
    is_blocked: bool | None = None
    ticket_status: TicketStatus | None = None
    ticket_type: TicketType | None = None
    id: int | None = None
    checkin_url: str | None = Field(None, description='URL de check-in')


class Lot1(BaseModel):
    id: int | None = None
    name: str | None = None


class Product9(BaseModel):
    id: int | None = None
    name: str | None = None


class EventParticipant(BaseModel):
    participant: Participant | None = None
    buyer: Buyer1 | None = None
    eticket: Eticket | None = None
    lot: Lot1 | None = None
    product: Product9 | None = None


class PaymentType1(StrEnum):
    """
    Tipo de pagamento para a negociação
    """

    BOLETO = 'BOLETO'
    PIX = 'PIX'


class Discount(BaseModel):
    type: str | None = Field(None, description='Tipo de desconto')
    value: float | None = Field(None, description='Valor do desconto')


class NegotiationRequest(BaseModel):
    subscription_id: int = Field(..., description='ID da assinatura')
    recurrences: list[int] = Field(
        ...,
        description='Números das recorrências em atraso (1 a 5 valores)',
        max_length=5,
        min_length=1,
    )
    payment_type: PaymentType1 = Field(
        ..., description='Tipo de pagamento para a negociação'
    )
    discount: Discount | None = None
    document: str | None = Field(
        None, description='CPF ou CNPJ do assinante (obrigatório para BOLETO)'
    )


class Payment2(BaseModel):
    type: str | None = Field(None, description='Tipo de pagamento')
    expiration_date: int | None = Field(
        None, description='Data de expiração (timestamp ms)'
    )
    pix_code: str | None = Field(None, description='Código PIX copia-e-cola')
    pix_qrcode: str | None = Field(None, description='QR code PIX')
    billet_url: str | None = Field(None, description='URL do boleto')
    billet_barcode: str | None = Field(None, description='Código de barras do boleto')


class NegotiationResponse(BaseModel):
    subscription_id: int | None = Field(None, description='ID da assinatura')
    transaction: str | None = Field(None, description='Código da transação gerada')
    payment: Payment2 | None = None
